const NEW_ICON_NAMES = {
	GOOGLE: 'google',
	FACEBOOK: 'facebook',
	MASKS_LOGO: 'masksLogo',
	BOOKMARK: 'bookmark',
	SHOPPING_CART: 'shoppingCart',
	USER: 'user',
	USER_WITH_CHEVRON: 'userWithChevron',
	ANNOTATION: 'annotation',
	EYE: 'eye',
	TRUCK: 'truck',
	BEAKER: 'beaker',
	CUBE: 'cube',
	GIFT: 'gift',
	IDENTIFICATION: 'identification',
	CURRENCY_DOLLAR: 'currency-dollar',
	CREDIT_CARD: 'credit-card',
	SEARCH: 'search',
	UPLOAD: 'upload',
	TRASH: 'trash',
}

export const ICON_NAMES = {
	TEST_ICON: 'test-icon',
	COMPANY_LOGO_ICON: 'companyLogo',
	REGISTER_ILLUSTRATION_ICON: 'registerIllustration',
	REGISTER_CONFIGURATION_ILLUSTRATION: 'registerCongratulationIllustration',
	FLAG_SH_ICON: 'flagSh',
	SMALL_LOGO_ICON: 'smallLogo',
	RESET_PASSWORD_LETTER_ICON: 'resetPasswordLetter',
	EYE_PASSWORD_ICON: 'eyePassword',
	EYE_PASSWORD_HIDE_ICON: 'eyePasswordHide',
	TRACK_YOUR_VITAL_ILLUSTRATION_1: 'trackYourVitalIllustration1',
	TRACK_YOUR_VITAL_ILLUSTRATION_2: 'trackYourVitalIllustration2',
	TRACK_YOUR_VITAL_ILLUSTRATION_3: 'trackYourVitalIllustration3',
	TRACK_YOUR_VITAL_ILLUSTRATION_4: 'trackYourVitalIllustration4',
	THANK_YOU_ILLUSTRATION: 'thankYouIllustration',
	PROFILE_ILLUSTRATION: 'profileIllustration',
	ICON_CHECK: 'iconCheck',
	ICON_DOC: 'iconDoc',
	BIRTHDAY_GENDER: 'birthday_gender',
	MAIL: 'mail',
	USER_ID: 'user_id',
	WEIGHT_HEIGHT: 'weight_height',
	ZIP: 'zip',
	TRIANGLE_DOWN: 'triangle_down',
	APPLE_DOWNLOAD: 'apple_download',
	ANDROID_DOWNLOAD: 'android_download',
	HAMBURGER: 'hamburger',
	CROSS: 'cross',
	...NEW_ICON_NAMES,
}
